"""Lazy public exports for NZ legal NLP fine-tuning workflows."""

from __future__ import annotations

from importlib import import_module

_EXPORT_MODULES: dict[str, str] = {
    "ArchitectureCandidate": "nlp_policy_nz.training.eval_arch",
    "ArchitectureEvaluation": "nlp_policy_nz.training.eval_arch",
    "ArchitectureMetrics": "nlp_policy_nz.training.eval_arch",
    "IsaacusAccessGate": "nlp_policy_nz.training.isaacus_adapter",
    "IsaacusDatasetManifest": "nlp_policy_nz.training.isaacus_adapter",
    "IsaacusModelManifest": "nlp_policy_nz.training.isaacus_adapter",
    "IsaacusRecord": "nlp_policy_nz.training.isaacus_adapter",
    "IsaacusToolManifest": "nlp_policy_nz.training.isaacus_adapter",
    "MaskedLanguageModelingCollator": "nlp_policy_nz.training.data",
    "MlebNzQuery": "nlp_policy_nz.training.isaacus_adapter",
    "ModelTrainingConfig": "nlp_policy_nz.training.trainers",
    "QLoRAConfig": "nlp_policy_nz.training.trainers",
    "SmokeTrainingResult": "nlp_policy_nz.training.smoke",
    "TrainingExecutionPlan": "nlp_policy_nz.training.runtime",
    "Track13EvidenceReport": "nlp_policy_nz.training.track13_evidence",
    "Track13ImplementationStatus": "nlp_policy_nz.training.track13_evidence",
    "SilverConsensus": "nlp_policy_nz.training.track13_silver",
    "OntologyConcept": "nlp_policy_nz.training.track13_silver",
    "SilverVote": "nlp_policy_nz.training.track13_silver",
    "Track20EvidenceReport": "nlp_policy_nz.training.track20_evidence",
    "Track21EvidenceReport": "nlp_policy_nz.training.track21_evidence",
    "Track22EvidenceReport": "nlp_policy_nz.training.track22_evidence",
    "Track74CaseScore": "nlp_policy_nz.training.track74_evaluation",
    "Track74EvaluationCase": "nlp_policy_nz.training.track74_evaluation",
    "Track74EvaluationManifest": "nlp_policy_nz.training.track74_evaluation",
    "Track74EvaluationReport": "nlp_policy_nz.training.track74_evaluation",
    "Track74TrainingDocument": "nlp_policy_nz.training.track74_evaluation",
    "Track75ArtifactLayout": "nlp_policy_nz.training.track75_finetune",
    "Track75ComparisonSummary": "nlp_policy_nz.training.track75_finetune",
    "Track75RunRecord": "nlp_policy_nz.training.track75_finetune",
    "Track53EvaluationContext": "nlp_policy_nz.training.track53_evidence",
    "Track53EvaluationDataset": "nlp_policy_nz.training.track53_evidence",
    "Track53HardwareConstraint": "nlp_policy_nz.training.track53_evidence",
    "Track53Metric": "nlp_policy_nz.training.track53_evidence",
    "Track53ModelCandidate": "nlp_policy_nz.training.track53_evidence",
    "Track53ModelComparisonManifest": "nlp_policy_nz.training.track53_evidence",
    "Track53ModelSelectionReport": "nlp_policy_nz.training.track53_evidence",
    "TrainingExample": "nlp_policy_nz.training.data",
    "TrainingHyperparameters": "nlp_policy_nz.training.trainers",
    "TrainingJobSpec": "nlp_policy_nz.training.trainers",
    "TrainingRuntimeProfile": "nlp_policy_nz.training.runtime",
    "TrainingSplitConfig": "nlp_policy_nz.training.data",
    "TrainingSplits": "nlp_policy_nz.training.data",
    "build_training_examples": "nlp_policy_nz.training.data",
    "classification_prf": "nlp_policy_nz.training.eval",
    "create_legal_bert_argument_component_job": "nlp_policy_nz.training.trainers",
    "create_legal_bert_mlm_job": "nlp_policy_nz.training.trainers",
    "create_legal_bert_stance_job": "nlp_policy_nz.training.trainers",
    "create_mlm_collator": "nlp_policy_nz.training.data",
    "create_qlora_job": "nlp_policy_nz.training.trainers",
    "choose_training_execution_plan": "nlp_policy_nz.training.runtime",
    "default_architecture_registry": "nlp_policy_nz.training.eval_arch",
    "default_isaacus_datasets": "nlp_policy_nz.training.isaacus_adapter",
    "default_isaacus_models": "nlp_policy_nz.training.isaacus_adapter",
    "default_isaacus_tools": "nlp_policy_nz.training.isaacus_adapter",
    "evaluate_track13_acceptance": "nlp_policy_nz.training.track13_evidence",
    "evaluate_track20_acceptance": "nlp_policy_nz.training.track20_evidence",
    "evaluate_track21_acceptance": "nlp_policy_nz.training.track21_evidence",
    "evaluate_track22_acceptance": "nlp_policy_nz.training.track22_evidence",
    "evaluate_track74_manifest": "nlp_policy_nz.training.track74_evaluation",
    "exact_match": "nlp_policy_nz.training.eval",
    "load_nz_mleb_fixture": "nlp_policy_nz.training.isaacus_adapter",
    "make_nz_mleb_query": "nlp_policy_nz.training.isaacus_adapter",
    "maori_token_integrity": "nlp_policy_nz.training.eval",
    "normalize_isaacus_record": "nlp_policy_nz.training.isaacus_adapter",
    "normalize_isaacus_records": "nlp_policy_nz.training.isaacus_adapter",
    "pareto_frontier": "nlp_policy_nz.training.eval_arch",
    "prepare_training_splits": "nlp_policy_nz.training.data",
    "rank_architectures": "nlp_policy_nz.training.eval_arch",
    "recommend_architecture": "nlp_policy_nz.training.eval_arch",
    "render_architecture_report": "nlp_policy_nz.training.eval_arch",
    "render_isaacus_integration_report": "nlp_policy_nz.training.isaacus_adapter",
    "render_isaacus_manifest_json": "nlp_policy_nz.training.isaacus_adapter",
    "render_track13_evidence_markdown": "nlp_policy_nz.training.track13_evidence",
    "aggregate_silver_votes": "nlp_policy_nz.training.track13_silver",
    "discover_provider_availability": "nlp_policy_nz.training.track13_silver",
    "detect_training_runtime": "nlp_policy_nz.training.runtime",
    "match_ontology_concepts": "nlp_policy_nz.training.track13_silver",
    "ontology_bridge_vote": "nlp_policy_nz.training.track13_silver",
    "render_track20_evidence_markdown": "nlp_policy_nz.training.track20_evidence",
    "render_track21_evidence_markdown": "nlp_policy_nz.training.track21_evidence",
    "render_track22_evidence_markdown": "nlp_policy_nz.training.track22_evidence",
    "render_track74_manifest_json": "nlp_policy_nz.training.track74_evaluation",
    "render_track74_report_json": "nlp_policy_nz.training.track74_evaluation",
    "render_track74_report_markdown": "nlp_policy_nz.training.track74_evaluation",
    "require_external_access": "nlp_policy_nz.training.isaacus_adapter",
    "to_pipeline_record": "nlp_policy_nz.training.isaacus_adapter",
    "validate_nz_mleb_fixture": "nlp_policy_nz.training.isaacus_adapter",
    "token_f1": "nlp_policy_nz.training.eval",
    "track13_acceptance_contract": "nlp_policy_nz.training.track13_evidence",
    "track13_implementation_status_contract": "nlp_policy_nz.training.track13_evidence",
    "track13_residual_external_gates": "nlp_policy_nz.training.track13_evidence",
    "track20_acceptance_contract": "nlp_policy_nz.training.track20_evidence",
    "track20_residual_external_gates": "nlp_policy_nz.training.track20_evidence",
    "track21_acceptance_contract": "nlp_policy_nz.training.track21_evidence",
    "track21_residual_external_gates": "nlp_policy_nz.training.track21_evidence",
    "track22_acceptance_contract": "nlp_policy_nz.training.track22_evidence",
    "track22_residual_external_gates": "nlp_policy_nz.training.track22_evidence",
    "default_track74_manifest": "nlp_policy_nz.training.track74_evaluation",
    "default_track74_evaluation_cases": "nlp_policy_nz.training.track74_evaluation",
    "default_track74_training_pool": "nlp_policy_nz.training.track74_evaluation",
    "score_track74_case": "nlp_policy_nz.training.track74_evaluation",
    "validate_track74_manifest": "nlp_policy_nz.training.track74_evaluation",
    "build_track75_run_record": "nlp_policy_nz.training.track75_finetune",
    "default_track75_artifact_layout": "nlp_policy_nz.training.track75_finetune",
    "default_track75_comparison_summary": "nlp_policy_nz.training.track75_finetune",
    "default_track75_config": "nlp_policy_nz.training.track75_finetune",
    "render_track75_closeout_markdown": "nlp_policy_nz.training.track75_finetune",
    "render_track75_model_card_markdown": "nlp_policy_nz.training.track75_finetune",
    "render_track75_run_record_json": "nlp_policy_nz.training.track75_finetune",
    "default_track53_evaluation_context": "nlp_policy_nz.training.track53_evidence",
    "default_track53_model_comparison_manifest": "nlp_policy_nz.training.track53_evidence",
    "evaluate_track53_selection": "nlp_policy_nz.training.track53_evidence",
    "render_track53_evaluation_context_json": "nlp_policy_nz.training.track53_evidence",
    "render_track53_model_comparison_manifest_json": "nlp_policy_nz.training.track53_evidence",
    "render_track53_selection_markdown": "nlp_policy_nz.training.track53_evidence",
    "render_track53_recommendation_markdown": "nlp_policy_nz.training.track53_evidence",
    "render_runtime_plan_json": "nlp_policy_nz.training.runtime",
    "render_parquet_smoke_training_json": "nlp_policy_nz.training.smoke",
    "render_smoke_training_json": "nlp_policy_nz.training.smoke",
    "run_cpu_mlm_smoke_training": "nlp_policy_nz.training.smoke",
    "run_cpu_mlm_smoke_training_from_parquet": "nlp_policy_nz.training.smoke",
    "track53_selection_contract": "nlp_policy_nz.training.track53_evidence",
}

__all__ = tuple(sorted(_EXPORT_MODULES))


def __getattr__(name: str) -> object:
    """Import public training helpers only when callers request them."""
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value
