"""Quality-infrastructure evidence helpers."""

from __future__ import annotations

from nlp_policy_nz.quality.monitoring import (
    DEFAULT_DRIFT_THRESHOLDS,
    DriftSignal,
    IngestionIssue,
    IngestionValidationResult,
    QualityReport,
    RecordQualityMetrics,
    build_quality_report,
    dashboard_rows,
    history_reports,
    load_quality_report,
    persist_quality_report,
    record_quality_metrics,
    register_quality_span_attributes,
    render_dashboard_html,
    report_to_json,
    validate_ingestion_input,
    validate_ingestion_inputs,
    write_dashboard_html,
)
from nlp_policy_nz.quality.track23_evidence import (
    Track23EvidenceReport,
    evaluate_track23_acceptance,
    render_track23_evidence_markdown,
    track23_acceptance_contract,
    track23_residual_external_gates,
)
from nlp_policy_nz.quality.track63_nlprule import (
    Track63EvaluationCase,
    Track63EvaluationResult,
    Track63EvidenceReport,
    Track63GrammarMatch,
    Track63GrammarRule,
    default_track63_cases,
    default_track63_rules,
    detect_track63_matches,
    evaluate_track63_acceptance,
    render_track63_evidence_markdown,
    run_track63_evaluation,
    track63_acceptance_contract,
    track63_match_to_extraction_record,
    track63_match_to_quality_issue,
    track63_residual_external_gates,
)

__all__ = [
    "DEFAULT_DRIFT_THRESHOLDS",
    "DriftSignal",
    "IngestionIssue",
    "IngestionValidationResult",
    "QualityReport",
    "RecordQualityMetrics",
    "Track23EvidenceReport",
    "Track63EvaluationCase",
    "Track63EvaluationResult",
    "Track63EvidenceReport",
    "Track63GrammarMatch",
    "Track63GrammarRule",
    "build_quality_report",
    "dashboard_rows",
    "default_track63_cases",
    "default_track63_rules",
    "detect_track63_matches",
    "evaluate_track23_acceptance",
    "evaluate_track63_acceptance",
    "history_reports",
    "load_quality_report",
    "persist_quality_report",
    "record_quality_metrics",
    "register_quality_span_attributes",
    "render_dashboard_html",
    "render_track23_evidence_markdown",
    "render_track63_evidence_markdown",
    "report_to_json",
    "run_track63_evaluation",
    "track23_acceptance_contract",
    "track23_residual_external_gates",
    "track63_acceptance_contract",
    "track63_match_to_extraction_record",
    "track63_match_to_quality_issue",
    "track63_residual_external_gates",
    "validate_ingestion_input",
    "validate_ingestion_inputs",
    "write_dashboard_html",
]
