"""Layout-aware OCR contracts and quality-aware routing."""

from .benchmark import BenchmarkCase, BenchmarkResult, BenchmarkThresholds, evaluate_benchmark
from .ensemble import (
    AdapterKind,
    AlignmentOperation,
    BoundingBox,
    CacheKey,
    CallableOCRAdapter,
    CascadeDecision,
    CascadePolicy,
    EngineAdapterSpec,
    LayoutBlock,
    OCRObservation,
    OCRToken,
    PageInput,
    QualityMetrics,
    TokenAlignment,
    build_cache_key,
    calculate_quality_metrics,
    compare_observations,
    normalize_reading_order,
    route_page,
)

__all__ = [
    "AdapterKind",
    "AlignmentOperation",
    "BenchmarkCase",
    "BenchmarkResult",
    "BenchmarkThresholds",
    "BoundingBox",
    "CacheKey",
    "CallableOCRAdapter",
    "CascadeDecision",
    "CascadePolicy",
    "EngineAdapterSpec",
    "LayoutBlock",
    "OCRObservation",
    "OCRToken",
    "PageInput",
    "QualityMetrics",
    "TokenAlignment",
    "build_cache_key",
    "calculate_quality_metrics",
    "compare_observations",
    "evaluate_benchmark",
    "normalize_reading_order",
    "route_page",
]
