"""Layout-aware OCR contracts and quality-aware routing."""

from nlp_policy_nz.ocr.cloud_ops import (
    BudgetLimits,
    CloudRunPlan,
    DriftAlert,
    LedgerRow,
    LedgerState,
    SignedRunReport,
    build_cloud_run_plan,
    build_drift_alerts,
    enforce_dispatch_limits,
    quarantine_failed,
    retry_failed,
    transition_row,
    verify_signed_run_report,
    write_signed_run_report,
)

from .benchmark import BenchmarkCase, BenchmarkResult, BenchmarkThresholds, evaluate_benchmark
from .ensemble import (
    AdapterKind,
    AlignmentOperation,
    BoundingBox,
    CacheKey,
    CallableOCRAdapter,
    CascadeDecision,
    CascadePolicy,
    EngineAdapterSpec,
    LayoutBlock,
    OCRObservation,
    OCRToken,
    PageInput,
    QualityMetrics,
    TokenAlignment,
    build_cache_key,
    calculate_quality_metrics,
    compare_observations,
    normalize_reading_order,
    route_page,
)

__all__ = [
    "AdapterKind",
    "AlignmentOperation",
    "BenchmarkCase",
    "BenchmarkResult",
    "BenchmarkThresholds",
    "BoundingBox",
    "BudgetLimits",
    "CacheKey",
    "CallableOCRAdapter",
    "CascadeDecision",
    "CascadePolicy",
    "CloudRunPlan",
    "DriftAlert",
    "EngineAdapterSpec",
    "LayoutBlock",
    "LedgerRow",
    "LedgerState",
    "OCRObservation",
    "OCRToken",
    "PageInput",
    "QualityMetrics",
    "SignedRunReport",
    "TokenAlignment",
    "build_cache_key",
    "build_cloud_run_plan",
    "build_drift_alerts",
    "calculate_quality_metrics",
    "compare_observations",
    "enforce_dispatch_limits",
    "evaluate_benchmark",
    "normalize_reading_order",
    "quarantine_failed",
    "retry_failed",
    "route_page",
    "transition_row",
    "verify_signed_run_report",
    "write_signed_run_report",
]
